language: node_js

node_js:
  - 8
  - 10

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: "${NPM_EMAIL}"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node: 10
    repo: "${TRAVIS_REPO_SLUG}"
    tags: true

notifications:
  slack:
    on_success: always
    rooms:
      secure: sbwjt1eyzARBirDqcTpbOEJOdO7RNDsfa+OKPH0cT2gZvzsjrkIu0RrJLy93wST41C5IVpQadDWKwJiDEdRtyuB4ZfjrCV48J6VMeFeVjNlHGpVGqSQNFDFtV40B2it2TvJr4yfPTsFRE+PqzkHgJuvZWAURWutP8SXDXL1KvrMMwiqxps32R6HAonDVx5fjiWmOFM0Wvmi35P5vLanQ/JeAF3Z0vXFTZ1C55i3WAkpQXRZKYE6nTDTIrU5CgiKomw7IczJQ0cFM0XXPJRHNTfos+vTk3ZZCAIUVRAL5MFO84LT9L6N8P19/xqcAJFYXuIFw1IVzO8NOtbxjgEZ3EXCZkHkBEMzUFHbAq+jzrpO74/G39c7ZmVB4qoWU84B/Xi/sNXyCwxy2zyXVSW0GzTjqNwa7wus1krh0dK8IRfilr6AgrA2p3e5hVzHXN/fy/Dd4pKnfu1lbFkvEvWa7/cz900BjVxCoZWJ2Jjta07jh4MVK/FtUsRkhJ5RV9vfo1BezlZ9+ZhtI6bIaHWsFD94K/2Ejod4uyHp60IX1TJedPUV3SX7F85d7pta11Afyk6TpvIV0G09wMdLIv+0BAZg2d2JJ9wsqgrbAyuySGuYyfrGmvB0rOGVKpPsuWdRc/qsuXXxI18K3t0ai3Mc61YC+uZVsdEGOIMQGhP19fjI=
