language: node_js

node_js:
  - 8
  - 10

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: "${NPM_EMAIL}"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node: 10
    repo: "${TRAVIS_REPO_SLUG}"
    tags: true

notifications:
  slack:
    on_success: always
    rooms:
      secure: aSYUPgoYYepgXPG3g64WEYEXhF0rRSAXoT9ZXVvWVzRktuZZLk/2j5ZU9AnNrEdKm7M5BDAL7CZA0CncZ1lh7lkBzQ6MuP9Nh2nb6wN9DoIsZrUNAjs5fipuv107t4e1dd6nkYEtbb7fgGBcRgrRNXHtF+PzyrnjSSaFKySeoHx+GA6TgQubH/B4VyfWBGMCkYhDg2fvwnhQrAQYb9iKtvnrZ5oasNvQGztj/idkrbUW1kCMsop1GpuYO0PKtk01EKETo1nFQ/F6Ch0AsS48NRct8otWxEsWt+mgxq/dKWJEzL8XP9WnbphAQs5xBjZiZhWXs9nZTeW0NGeSxLs/NUzdkdA7fiRLZ6L+8ftBwLyUzDAYw3+vBfOAbuMRzsani9CIKymGo4EkXIv4P/Y+k14u1puVaNXHYADl8ujttHa/KmXz3uQto/xqjLJT46HlrKifn+lImTWGXrnpXJiVru94xhJ6LXW0buiNO+WUMfj79JDpYnlH2B+zhtibC68dlzfqoWFOnoEXzZYapYk0Z2XZo0iPoyjfsH0sayj/qS9MQlec1dYGa1mAE1A/tvlkvG9N0VRfsZ+9PIXa5yE865iL5rx5Gr9US3e+H204ckYN49TYdk5N6SEuz6m7tJf7YEWDME4pzi+XA2syV7NcOmsqKrcDW5fnRt/bkTGxYno=
